schema_version = "1.0.0"
id = "draw_to_keys"
version = "1.0.0"
name = "Draw to Keys"
tagline = "Convert annotation strokes into keyframes"
maintainer = "TheMultiX PGDM"
type = "add-on"

website = "https://github.com/TheMultiXPGDM/Draw-to-Keys"
tags = ["Animation", "3D View"]
blender_version_min = "5.1.0"

license = ["SPDX:GPL-3.0-or-later"]
